version: '3.8'

services:
  bitcoin-regtest:
    container_name: bitcoin-regtest
    build:
      context: ./docker/bitcoin
      dockerfile: Dockerfile
    restart: unless-stopped
    stop_grace_period: 30s
    networks:
      - bitcoin-regtest
    ports:
      - "127.0.0.1:28336:28332/tcp"  # RPC (was 28332)
      - "0.0.0.0:28337:28333/tcp"    # RPC (was 28333)
    command: >
      -printtoconsole
      -datadir=/app/data
      -regtest
      -blockversion=536870912
    volumes:
      - "./data/regtest/bitcoin:/app/data"
      - "./bitcoin-regtest.conf:/app/data/bitcoin.conf:ro"

  public-pool-regtest:
    container_name: public-pool-regtest
    build:
      context: ..
      dockerfile: Dockerfile
    restart: unless-stopped
    stop_grace_period: 30s
    networks:
      - bitcoin-regtest
    ports:
      - "0.0.0.0:23333:23333/tcp"
      - "127.0.0.1:23338:23334/tcp"  # Stratum (was 23334)
    volumes:
      - "./data/regtest/public-pool:/public-pool/DB"
      - "./public-pool-regtest.env:/public-pool/.env:ro"
    environment:
      - NODE_ENV=production

networks:
  bitcoin-regtest:
